name: Run App

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      password: ${{ secrets.password }}
      api_key: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: python main.py
